language: node_js
node_js:
  - '8'
dist: trusty
before_install: |
  set -e
  export PATH="./$HOME/node_modules/.bin:$PATH"
  npm install -g @alrra/travis-scripts
  date
install: |
  set -ev
  date
  ./.travis/install.sh
  date
script: ./.travis/script.sh
after_failure: |
  tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
deploy:
  provider: script
  script: ./.travis/deploy.sh
  skip_cleanup: true
  on:
      all_branches: true
cache:
  directories:
    - node_modules
sudo: required